### ISSUE TITLE
Migration to version 10.0

### ISSUE THREAD

**Issue by renatonlima** [akretion/payment-gateway#7]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0

# Modules to migrate

- [x] payment_gateway
- [x] payment_gateway_paypal
- [x] payment_gateway_stripe
- [ ] sale_quick_payment_gateway
